name: CI

on:
  push:
    paths-ignore:
      - '**.adoc'
  pull_request:
    paths-ignore:
      - '**.adoc'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Check gradle-wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Cache
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: jdk11

      - name: Build
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: jdk11
          arguments: build
          properties: |
            release.useLastTag=${{ startsWith(github.ref, 'refs/tags/v') }}
          read-only: ${{ github.ref != 'refs/heads/main' }}
          execution-only-caches: true

      - name: Publish release to GitHub Packages
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: jdk11
          arguments: |
            --init-script .github/publishing-ghp.init.gradle.kts
            publish
          properties: |
            release.useLastTag=true
          read-only: true
          execution-only-caches: true
        env:
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_PASSWORD: ${{ github.token }}

      - name: Publish release to Gradle Plugin Portal
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: jdk11
          arguments: |
            publishPlugin
          properties: |
            release.useLastTag=true
            gradle.publish.key=${{ secrets.GRADLE_PLUGIN_PORTAL_KEY }}
            gradle.publish.secret=${{ secrets.GRADLE_PLUGIN_PORTAL_SECRET }}
          read-only: true
          execution-only-caches: true
