name: CI

on:
  push:
    paths-ignore:
      - '**.adoc'
  pull_request:
    paths-ignore:
      - '**.adoc'

jobs:
  wrapper:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

  build:
    runs-on: ubuntu-latest
    needs:
      - wrapper

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            -Prelease.useLastTag=${{ startsWith(github.ref, 'refs/tags/v') }}
            build
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Publish release to GitHub Packages
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            --init-script .github/publishing-ghp.init.gradle.kts
            -Prelease.useLastTag=true
            publish
          cache-read-only: true
        env:
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_PASSWORD: ${{ github.token }}

      - name: Publish release to Gradle Plugin Portal
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            -Prelease.useLastTag=true
            -Pgradle.publish.key=${{ secrets.GRADLE_PLUGIN_PORTAL_KEY }}
            -Pgradle.publish.secret=${{ secrets.GRADLE_PLUGIN_PORTAL_SECRET }}
            publishPlugins
          cache-read-only: true
