name: CI

on:
  push:
    paths-ignore:
      - '**.adoc'
  pull_request:
    paths-ignore:
      - '**.adoc'

env:
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: temurin

jobs:
  wrapper:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

  build:
    name: Build and Release
    runs-on: ubuntu-latest
    needs:
      - wrapper

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Build
        run: |
          ./gradlew build -Prelease.useLastTag=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Publish release to Gradle Plugin Portal
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          ./gradlew publishPlugins -Prelease.useLastTag=true
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.gradle_plugin_portal_key }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.gradle_plugin_portal_secret }}

      - name: Zulip notification
        uses: zulip/github-actions-zulip/send-message@v1
        if: ${{ startsWith(github.ref, 'refs/tags/v') && always() }}
        with:
          api-key: ${{ secrets.zulip_api_key }}
          email: ${{ secrets.zulip_email }}
          organization-url: ${{ secrets.zulip_url }}
          type: stream
          to: dev
          topic: GitHub Notifications
          content: |
            **${{ github.repository }}** release ${{ github.ref_name }} *${{ job.status }}*

            Release [`${{ github.ref_name }}`](${{ env.BASE_URL }}/tree/${{ github.ref_name }})

            JDK: *${{ env.JAVA_VERSION }}* (${{ env.JAVA_DISTRIBUTION }})

            Workflow run ${{ env.BASE_URL }}/actions/runs/${{ github.run_id }}
        env:
          BASE_URL: ${{ github.server_url }}/${{ github.repository }}
